[project]
name = "l39"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "tensorflow>=2.19.0",
    "tensorflow-datasets>=4.9.9",
    "pillow>=10.0.0",
    "matplotlib>=3.10.8",
]
